version: 0.2
env:
    parameter-store:
        S3_BUCKET_URI: "s3_bucket_uri"
phases:
    install:
        commands:
            - wget https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_amd64.deb -O /tmp/hugo.deb #TODO: Make this wget change on new releases
            - sudo dpkg -i /tmp/hugo.deb
            - git clone --recurse-submodules https://github.com/rootkit-ty/rootkitty.tech
            - cd rootkitty.tech
    build:
        commands:
            - hugo
    post_build:
        commands:
            - aws s3 rm $S3_BUCKET_URI --recursive
            - aws s3 cp public/ $S3_BUCKET_URI --recursive
